### ISSUE TITLE
테스트 - 옷 추가

### ISSUE THREAD

**Issue by pineoc** [pineoc/CodingProjServer#19]
옷 추가하고 파일 잘 추가 되었는지 테스트

**Comment by ICoi** [comment]
현재 파일 추가 안되는 상태 !!
따라서 상태 보류! -> 파일 추가 확인 후 여러개 파일 올라가는거 기능 구현필요!

**Comment by ICoi** [comment]
파일 추가 기능 구현! 
여러개 추가되는 기능은 아직 미구현..
