### ISSUE TITLE
해야할일

### ISSUE THREAD

**Issue by hsw2012s** [pineoc/CodingProjServer#25]
1.에디터페이지
2.글쓰기 페이지수정
3.카테고리 페이지 수정

카테고리페이지는 테이블 디자인을 살짝 바꿀필요성이 있고 글쓰기 페이지는 썸네일,타이틀 선택부분 추가, 에디터 페이지는 관리자 페이지의 기본디자인을 이용하되 색놀이를 해야함

**Comment by pineoc** [comment]
에디터 추가 페이지에 필요한 데이터 주는거 넣을테니
카테고리 스피너 만들기 해야함
글쓰기페이지에서도 카테고리 스피너 만들어야할듯
